OSC output message formatting
Xmodal/autonomX pull request #333
Opened 2021-07-15 22:03 UTC by jvlyndark

2021-07-16 14:00 UTC, aalex requested changes
Can you add a comment saying what is the format of the OSC message(s) sent here?

2021-07-16 14:00 UTC, aalex commented on autonomx/ComputeEngine.cpp
> +            emit sendOscData((*it)->getID(), oscOutputRegion);
Can you add a comment saying what is the format of the OSC message(s) sent here?

2021-07-16 14:00 UTC, aalex commented on autonomx/ComputeEngine.cpp
> +        emit sendOscData((*it)->getID(), oscOutputsList);
Can you add a comment saying what is the format of the OSC message(s) sent here?

2021-07-16 16:35 UTC, aalex approved these changes
LGTM

2021-07-16 16:36 UTC, netherwaves requested changes
will LGTM with this very very tiny change (sorry!)
- the packed OSC address should be `[...]/outputs` (with an "s" at the end) to distinguish it fully from the individual message address. this isn't critical but i think it clears a virtual point of confusion

2021-07-16 19:31 UTC, aalex commented
Good idea. @jvlyndark Can you also make sure to edit the OSC.md file according to this new interface? (it can be done in another PR, if you prefer)

2021-07-19 20:35 UTC, netherwaves approved these changes
i've been convinced (also sorry)

2021-07-20 01:32 UTC, merged