fix app-breaking bug
Xmodal/autonomX pull request #364
Opened 2021-08-18 15:04 UTC by netherwaves

2021-08-18 16:52 UTC, aalex requested changes
I would put that statement in two separate lines and add a semicolon after each.

allowSnapW = false;
allowSnapH = false;

2021-08-18 16:52 UTC, aalex commented on autonomx/layout/LatticeView.qml
> +        allowSnapW = allowSnapH = false
I would put that statement in two separate lines and add a semicolon after each.

allowSnapW = false;
allowSnapH = false;

2021-08-19 18:25 UTC, jvlyndark approved these changes
LGTM

2021-08-19 21:28 UTC, aalex approved these changes
LGTM

2021-08-19 22:34 UTC, merged